import './globals.css';
import { DM_Sans , Sora } from 'next/font/google';

const sans = DM_Sans({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
});

const sora = Sora({
  subsets: ['latin'],
  variable: '--font-sora',
  display: 'swap',
});


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
import SessionProvider from '../providers/SessionProvider';
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sans.variable} ${sora.variable}`}>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
