
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import SessionProvider from "../providers/SessionProvider"
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        
        <SessionProvider>{children}</SessionProvider>
        
        </body>
    </html>
  );
}
